#Generates MI and T scores for bigrams and trigrams of given year
#MI scores favor rare n-grams, so this calculation only looks at n-grams that occur 10+ times
#T scores favor common n-grams. This calculation looks at n-grams occuring <20 times
#Uses file name conventions generated by start.sh
#input: folder path, keyword
#example: sh scores_ln.sh 2010 pp => generate prepol scores inside pp folder

mkdir -p $1/$2
#N = total words
N= cat $1/$2_tokens.txt | wc -l

#MI Score for bigrams
cat $1/$2_bigrams.txt | awk '$1 > 10' >  $1/$2/bigrams_common.tmp
cat $1/$2_unigrams.txt $1/$2/bigrams_common.tmp | awk 'NF==2 {c[$2]=$1} NF==3 {print log($N*$1/(c[$2]*c[$3]))/log(2), c[$2], c[$3], $0}' | sort -n > $1/$2/MI_bigrams.txt

#T Score for bigrams
cat $1/$2_bigrams.txt | awk '$1 < 20' > $1/$2/bigrams_rare.tmp
cat $1/$2_unigrams.txt $1/$2/bigrams_rare.tmp |awk 'NF==2 {c[$2]=$1} NF==3 {print ($1-(c[$2]*c[$3])/ $N)/sqrt($1), c[$2], c[$3], $0}'| sort -n > $1/$2/T_bigrams.txt